import swaggerJSDoc,{OAS3Definition,OAS3Options} from "swagger-jsdoc";


const swaggerDefinition:OAS3Definition={
    openapi: "3.0.0",
    info:{
        title: "Documentacion de la API",
        version: "1.0.0",
    },
    servers:[
        {
            url:"https://health-tracker-backend-production.up.railway.app"
        },
    ],
    components:{
        securitySchemes:{
            bearerAuth:{
                type:"http",
                scheme:"bearer",
            },
        },
        schemas:{
            user:{
                type:"object",
                required:["correo","password"],
                properties:{
                    correo:{
                        type:"string",
                    },
                    password:{
                        type:"string",
                    },
                },
            },
            doctor:{
                type:"object",
                required:["name","last_name","dni","celular","correo","password"],
                properties:{
                    name:{
                        type:"string",
                    },
                    last_name:{
                        type:"string",
                    },
                    dni:{
                        type:"string",
                    },
                    celular:{
                        type:"string",
                    },
                    users:{
                        type:"object",
                        properties:{
                            correo:{
                                type:"string",
                            },
                            password:{
                                type:"string",
                            },
                        },
                    },
                },
            },
            paciente:{
                type:"object",
                required:["nombre","dni","edad","celular","correo","password"],
                properties:{
                    nombre:{
                        type:"string",
                    },
                    dni:{
                        type:"string",
                    },
                    edad:{
                        type:"integer"
                    },
                    celular:{
                        type:"string",
                    },
                    users:{
                        type:"object",
                        properties:{
                            correo:{
                                type:"string",
                            },
                            password:{
                                type:"string",
                            },
                        },
                    },
                },
            },
            pastillas:{
                type:"object",
                required:["nombre","dosis"],
                properties:{
                    nombre:{
                        type:"string",
                    },
                    dosis:{
                        type:"string",
                    },
                },
            },
            recordatorio:{
                type:"object",
                required:["fecha_inicio","fecha_fin","interval","message","medicamento","paciente"],
                properties:{
                    fecha_inicio:{
                        type:"Date",
                    },
                    fecha_fin:{
                        type:"Date",
                    },
                    interval:{
                        type:"string",
                    },
                    message:{
                        type:"string",
                    },
                    medicamento:{
                        type:"integer",
                    },
                    paciente:{
                        type:"integer",
                    },
                },
            },
            login:{
                type: "object",
                required:["correo","password"],
                properties:{
                    correo:{
                        type:"string"
                    },
                    password:{
                        type:"string"
                    },
                },
            },
        }
    }
};

const swaggerOptions:OAS3Options={
    swaggerDefinition,
    apis:["./src/components/*/index.ts"],
};

export default swaggerJSDoc(swaggerOptions)